services:
  telegram-userbot:
    build: .
    container_name: telegram-userbot
    restart: unless-stopped
    
    # Монтируем volumes для сохранения данных
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./sessions:/app/sessions
      - ./.env:/app/.env:ro
      - ./session_string.txt:/app/session_string.txt:ro  # Монтируем строку сессии
    
    # Переменные окружения
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
    
    # Настройки ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Настройки логирования
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Сеть
    networks:
      - userbot-network
    
    # Команда для запуска
    command: python main_pipeline.py

networks:
  userbot-network:
    driver: bridge
